name: Build & Push

on:
  workflow_dispatch:   # позволяет запускать вручную
  push:
    branches:
      - test          # автоматически при пуше в ветку test

jobs:
  build-and-push:
    runs-on: self-hosted

    steps:
    - name: Clonar repositorio
      uses: actions/checkout@v3
      with:
        ref: test

    - name: Login a Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Construir y push Docker-image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: dimafp/dmytro.zhekov_daw-web:latest

    - name: Detener contenedor anterior (si existe)
      run: |
        try { docker stop daw-web } catch {}
        try { docker rm daw-web } catch {}

    - name: Arrancar contenedor local
      run: |
        docker run -d --name daw-web -p 8888:80 dimafp/dmytro.zhekov_daw-web:latest
